-- Create State Teams Script (Simple Version)
-- Run this in Supabase SQL editor to create all US state teams
-- If teams already exist, you may get duplicate errors - that's okay

-- Temporarily disable RLS for teams table
ALTER TABLE teams DISABLE ROW LEVEL SECURITY;

-- Clear existing state teams (optional - uncomment if you want to recreate)
-- DELETE FROM teams WHERE badges @> ARRAY['state_team'];

-- Insert all 50 US state teams
INSERT INTO teams (name, description, category, level, privacy, max_members, admin_id, color_theme, badges, rules) VALUES
('Alabama Fitness Community', 'Official fitness community for Alabama residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Alaska Fitness Community', 'Official fitness community for Alaska residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Arizona Fitness Community', 'Official fitness community for Arizona residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Arkansas Fitness Community', 'Official fitness community for Arkansas residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('California Fitness Community', 'Official fitness community for California residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Colorado Fitness Community', 'Official fitness community for Colorado residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Connecticut Fitness Community', 'Official fitness community for Connecticut residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Delaware Fitness Community', 'Official fitness community for Delaware residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Florida Fitness Community', 'Official fitness community for Florida residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Georgia Fitness Community', 'Official fitness community for Georgia residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Hawaii Fitness Community', 'Official fitness community for Hawaii residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Idaho Fitness Community', 'Official fitness community for Idaho residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Illinois Fitness Community', 'Official fitness community for Illinois residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Indiana Fitness Community', 'Official fitness community for Indiana residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Iowa Fitness Community', 'Official fitness community for Iowa residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Kansas Fitness Community', 'Official fitness community for Kansas residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Kentucky Fitness Community', 'Official fitness community for Kentucky residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Louisiana Fitness Community', 'Official fitness community for Louisiana residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Maine Fitness Community', 'Official fitness community for Maine residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Maryland Fitness Community', 'Official fitness community for Maryland residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Massachusetts Fitness Community', 'Official fitness community for Massachusetts residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Michigan Fitness Community', 'Official fitness community for Michigan residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Minnesota Fitness Community', 'Official fitness community for Minnesota residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Mississippi Fitness Community', 'Official fitness community for Mississippi residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Missouri Fitness Community', 'Official fitness community for Missouri residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Montana Fitness Community', 'Official fitness community for Montana residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Nebraska Fitness Community', 'Official fitness community for Nebraska residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Nevada Fitness Community', 'Official fitness community for Nevada residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('New Hampshire Fitness Community', 'Official fitness community for New Hampshire residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('New Jersey Fitness Community', 'Official fitness community for New Jersey residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('New Mexico Fitness Community', 'Official fitness community for New Mexico residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('New York Fitness Community', 'Official fitness community for New York residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('North Carolina Fitness Community', 'Official fitness community for North Carolina residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('North Dakota Fitness Community', 'Official fitness community for North Dakota residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Ohio Fitness Community', 'Official fitness community for Ohio residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Oklahoma Fitness Community', 'Official fitness community for Oklahoma residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Oregon Fitness Community', 'Official fitness community for Oregon residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Pennsylvania Fitness Community', 'Official fitness community for Pennsylvania residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Rhode Island Fitness Community', 'Official fitness community for Rhode Island residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('South Carolina Fitness Community', 'Official fitness community for South Carolina residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('South Dakota Fitness Community', 'Official fitness community for South Dakota residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Tennessee Fitness Community', 'Official fitness community for Tennessee residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Texas Fitness Community', 'Official fitness community for Texas residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Utah Fitness Community', 'Official fitness community for Utah residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Vermont Fitness Community', 'Official fitness community for Vermont residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Virginia Fitness Community', 'Official fitness community for Virginia residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Washington Fitness Community', 'Official fitness community for Washington residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('West Virginia Fitness Community', 'Official fitness community for West Virginia residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Wisconsin Fitness Community', 'Official fitness community for Wisconsin residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']),
('Wyoming Fitness Community', 'Official fitness community for Wyoming residents and fitness enthusiasts. Connect with local members, share workouts, and compete in state-wide challenges!', 'Regional Community', 'All Levels', 'Public', 1000, '00000000-0000-0000-0000-000000000000', ARRAY['#10B981', '#059669'], ARRAY['state_team', 'official'], ARRAY['Be respectful to all community members', 'Share your fitness journey and progress', 'Support and encourage fellow state members', 'Keep discussions fitness and health related', 'Follow community guidelines and terms of service']);

-- Re-enable RLS for teams table
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

-- Show created teams
SELECT name, category, privacy, max_members, created_at 
FROM teams 
WHERE badges @> ARRAY['state_team'] 
ORDER BY name;








