// src/pages/AIPlans.jsx
import { useState } from "react";
import { BrainCircuit } from "lucide-react";

/* ------------------------------------------------
   Placeholder hook: replace with real premium check
   (Stripe subscription status, etc.)
------------------------------------------------- */
function usePremium() {
  const [isPremium] = useState(false); // ⬅️ change to true if testing premium
  return isPremium;
}

export default function AIPlans() {
  const isPremium = usePremium();

  if (!isPremium) {
    return (
      <div className="relative p-6">
        {/* Blurred locked preview */}
        <div className="blur-sm pointer-events-none select-none">
          <LockedAIPlansPreview />
        </div>

        {/* Upgrade overlay */}
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="bg-white border border-gray-300 shadow-lg rounded-2xl p-6 text-center max-w-sm">
            <h2 className="text-xl font-bold text-gray-900 mb-2">
              Upgrade to Premium
            </h2>
            <p className="text-gray-600 mb-4">
              Unlock your personalized AI Coach and workout plans.
            </p>
            <a
              href="/pricing"
              className="inline-block bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-semibold"
            >
              Upgrade Now
            </a>
          </div>
        </div>
      </div>
    );
  }

  // Premium users see the full AI Coach
  return <AIPlansContent />;
}

/* ------------------------------------------------
   Locked Preview (blurred placeholder)
------------------------------------------------- */
function LockedAIPlansPreview() {
  return (
    <div className="p-6 rounded-2xl border border-gray-200 bg-gray-50">
      <div className="flex items-center gap-3 mb-4">
        <BrainCircuit className="h-6 w-6 text-gray-400" />
        <h1 className="text-2xl font-bold text-gray-400">
          AI Coach (Locked)
        </h1>
      </div>
      <p className="text-gray-500">
        Get daily AI-generated workout and nutrition plans tailored to your goals.
      </p>
    </div>
  );
}

/* ------------------------------------------------
   Full AI Plans (Premium)
------------------------------------------------- */
function AIPlansContent() {
  // ⬇️ Example placeholder logic until you add real AI plan generation
  const examplePlans = [
    { day: "Monday", workout: "Push Day - Bench, OHP, Dips" },
    { day: "Tuesday", workout: "Pull Day - Deadlifts, Rows, Pull-ups" },
    { day: "Wednesday", workout: "Leg Day - Squats, Lunges, Calf Raises" },
  ];

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <BrainCircuit className="h-8 w-8 text-slate-700" />
        <h1 className="text-3xl font-bold text-slate-900">AI Coach</h1>
      </div>
      <p className="text-slate-600">
        Your personalized workout and nutrition plans generated by AI.
      </p>

      {/* Example plan list */}
      <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
        <h2 className="text-lg font-semibold text-slate-900 mb-3">
          Weekly Plan
        </h2>
        <ul className="space-y-3">
          {examplePlans.map((plan, idx) => (
            <li
              key={idx}
              className="rounded-lg border border-slate-200 p-3 bg-slate-50"
            >
              <div className="font-semibold text-slate-800">{plan.day}</div>
              <div className="text-sm text-slate-600">{plan.workout}</div>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
