-- AI Plans Table
create table if not exists ai_plans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  type text not null,
  details text not null,
  premium boolean default false
);

-- Index for quick lookups
create index if not exists ai_plans_user_id_idx on ai_plans(user_id);
