-- Weight Logs Table
create table if not exists weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  weight_kg numeric not null
);

-- Burn Logs Table
create table if not exists burn_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  calories_burned int not null
);

-- Badges Table
create table if not exists badges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  badge_name text not null,
  created_at timestamp with time zone default now()
);
