-- Communities Table
create table if not exists communities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default now()
);

-- Community Members Table
create table if not exists community_members (
  id bigint generated by default as identity primary key,
  community_id bigint references communities(id),
  user_id uuid references auth.users not null,
  role text default 'member',
  joined_at timestamp with time zone default now()
);

-- Community Messages Table
create table if not exists community_messages (
  id bigint generated by default as identity primary key,
  community_id bigint references communities(id),
  user_id uuid references auth.users not null,
  message text not null,
  created_at timestamp with time zone default now()
);

-- Feed Events Table
create table if not exists community_feed (
  id bigint generated by default as identity primary key,
  community_id bigint references communities(id),
  user_id uuid references auth.users not null,
  event_type text not null,
  details text,
  created_at timestamp with time zone default now()
);
