-- Food Logs Table
create table if not exists food_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  name text not null,
  grams int not null,
  calories int not null,
  protein int not null,
  carbs int not null,
  fat int not null
);

-- Index for user lookup
create index if not exists food_logs_user_id_idx on food_logs(user_id);
