-- Exercises Table
create table if not exists exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  equipment text
);

-- Workouts Table
create table if not exists workouts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  exercise_id bigint references exercises(id),
  sets int not null,
  reps int not null,
  weight numeric not null,
  volume numeric not null
);

-- PR History Table
create table if not exists pr_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  exercise_id bigint references exercises(id),
  weight numeric not null,
  reps int not null,
  created_at timestamp with time zone default now()
);

-- Seed some exercises
insert into exercises (name, category, equipment)
values
  ('Bench Press', 'Chest', 'Barbell'),
  ('Squat', 'Legs', 'Barbell'),
  ('Deadlift', 'Back', 'Barbell'),
  ('Overhead Press', 'Shoulders', 'Barbell'),
  ('Barbell Row', 'Back', 'Barbell'),
  ('Pull Ups', 'Back', 'Bodyweight'),
  ('Bicep Curls', 'Arms', 'Dumbbell'),
  ('Tricep Extensions', 'Arms', 'Cable')
on conflict do nothing;
